name: gemchat
description: GemChat, Your doorway to conversing with Google's Gemini AI through Telegram. Seamlessly chat with AI.

version: 1.0.0
repository: https://github.com/HeySreelal/gemchat

environment:
  sdk: ^3.2.6

dependencies:
  google_generative_ai: ^0.2.0
  televerse: ^1.13.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
